<?php


namespace Convert;

use Convert\toRomanNumber;
use PHPUnit\Framework\TestCase;


/**
 * Class toRomanumber
 *
 * @package Azet\Review\test\service
 * @testdox number conversion
 */
class toRomanumberTest extends TestCase
{
    /** @var toRomanNumber */
    private $service;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->service = new toRomanNumber();
    }

    /** @testdox test for correct returnType */
    public function testReturnType()
    {
        $result = $this->service->convertToRomanNum(10);
        $this->assertIsString($result, gettype(10));
    }

    /** @testdox test for correct Addition */
    public function testaddition()
    {
        $result = $this->service->convertToRomanNum(10);
        $this->assertEquals('X', $result);
    }

    /** @testdox test for correct Substraction */
    public function testSubstraction()
    {
        $result = $this->service->convertToRomanNum(2019);
        $this->assertEquals('MMXIX', $result);
    }


}